spring:
  datasource:
    default-catalog: db
    url: jdbc:h2:~/test110
    data-username: sa
    data-password:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      implicit-naming-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      format-sql: true
      show-sql: true
      globally-quoted-identifiers: true
      ddl-auto: update

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

server:
  localFront: http://localhost:4200